exclude: ^(vendor|server/assets/vendor)/

repos:
  - repo: builtin
    hooks:
      - id: end-of-file-fixer
        exclude: &fixtures ^(render/testdata|search/testdata|examples/data)/
      - id: trailing-whitespace
        exclude: *fixtures
      - id: detect-private-key
      - id: check-yaml

  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
        args: [-formatter, retain_line_breaks_single=true]

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        language: system
        entry: prettier --write
        files: ^README\.md$

      - id: gofmt
        name: gofmt
        entry: gofmt -s -w
        language: system
        types: [go]

      - id: go-vet
        name: go vet
        entry: go vet
        args: ["./..."]
        language: system
        pass_filenames: false
        always_run: true

      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run
        args: ["./..."]
        language: system
        pass_filenames: false
        always_run: true
