package render

import (
	"bytes"
	"strings"

	"github.com/alecthomas/chroma/v2"
	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/styles"
	highlighting "github.com/yuin/goldmark-highlighting/v2"
	"github.com/yuin/goldmark/ast"
	"github.com/yuin/goldmark/renderer"
	"github.com/yuin/goldmark/renderer/html"
	"github.com/yuin/goldmark/util"
)

// codeStyle is the light chroma style; the dark one is its registered
// counterpart, so only one name is configured here.
const codeStyle = "github"

// languageAliases maps fence info strings the corpus uses onto chroma lexer
// names. The Cyrillic "с" is a real typo in python/python-notes-index.md.
var languageAliases = map[string]string{
	"с":              "c", // U+0441 CYRILLIC SMALL LETTER ES
	"docker-compose": "yaml",
	"cmd":            "batch",
	"regexp":         "regex",
}

// codeWrapper wraps every fenced block in a container carrying the language,
// so the frontend can render a label and a copy button. When chroma did not
// highlight the block (no language, or a language it does not know) the
// extension leaves the <pre><code> to us.
func codeWrapper(w util.BufWriter, ctx highlighting.CodeBlockContext, entering bool) {
	lang, hasLang := ctx.Language()
	if entering {
		_, _ = w.WriteString(`<div class="code-block"`)
		if hasLang && len(lang) > 0 {
			_, _ = w.WriteString(` data-lang="`)
			_, _ = w.Write(util.EscapeHTML(lang))
			_ = w.WriteByte('"')
		}
		writeSrcRangeAttrs(w, ctx.Attributes())
		_ = w.WriteByte('>')
		if !ctx.Highlighted() {
			_, _ = w.WriteString(`<pre tabindex="0" class="chroma"><code>`)
		}
		return
	}
	if !ctx.Highlighted() {
		_, _ = w.WriteString("</code></pre>")
	}
	_, _ = w.WriteString("</div>\n")
}

// writeSrcRangeAttrs writes the source range of a fenced block, which the
// highlighting extension hands over as its own attribute view of the node.
func writeSrcRangeAttrs(w util.BufWriter, attrs highlighting.ImmutableAttributes) {
	if attrs == nil {
		return
	}
	for _, name := range srcRangeAttrs {
		if value, ok := attrs.GetString(name); ok {
			writeSrcAttr(w, name, value)
		}
	}
}

// indentedCodeRenderer gives an indented code block the same container as a
// fenced one. The highlighting extension only handles fenced blocks, so
// without this the two look nothing alike.
type indentedCodeRenderer struct{}

func (r *indentedCodeRenderer) RegisterFuncs(reg renderer.NodeRendererFuncRegisterer) {
	reg.Register(ast.KindCodeBlock, r.render)
}

func (r *indentedCodeRenderer) render(
	w util.BufWriter, source []byte, n ast.Node, entering bool,
) (ast.WalkStatus, error) {
	if !entering {
		_, _ = w.WriteString("</code></pre></div>\n")
		return ast.WalkContinue, nil
	}
	_, _ = w.WriteString(`<div class="code-block"`)
	writeSrcRange(w, n)
	_, _ = w.WriteString(`><pre tabindex="0" class="chroma"><code>`)
	lines := n.Lines()
	for i := range lines.Len() {
		line := lines.At(i)
		html.DefaultWriter.RawWrite(w, line.Value(source))
	}
	return ast.WalkContinue, nil
}

// ChromaCSS is the syntax-highlighting stylesheet: the light theme on bare
// :root, the dark one applied twice, once under prefers-color-scheme with an
// explicit light choice opting out, and once under [data-theme="dark"] so the
// toggle wins in both directions. Same pattern as the design tokens.
func ChromaCSS() []byte {
	light := styles.GetForMode(codeStyle, chroma.Light)
	dark := styles.GetForMode(codeStyle, chroma.Dark)

	var out bytes.Buffer
	out.WriteString("/* syntax highlighting, generated by chroma */\n")
	writeChromaRules(&out, light, ":root")
	out.WriteString("\n@media (prefers-color-scheme: dark) {\n")
	writeChromaRules(&out, dark, `:root:not([data-theme="light"])`)
	out.WriteString("}\n\n")
	writeChromaRules(&out, dark, `:root[data-theme="dark"]`)
	return out.Bytes()
}

// writeChromaRules prefixes every selector with scope. chroma emits one rule
// per line and never puts a comma in a selector, so this stays a string edit.
func writeChromaRules(out *bytes.Buffer, style *chroma.Style, scope string) {
	formatter := chromahtml.New(
		chromahtml.WithClasses(true),
		chromahtml.WithCSSComments(false),
		chromahtml.WithAllClasses(true),
	)
	var raw bytes.Buffer
	if err := formatter.WriteCSS(&raw, style); err != nil {
		return
	}
	for line := range strings.SplitSeq(strings.TrimSpace(raw.String()), "\n") {
		brace := strings.Index(line, "{")
		if brace < 0 {
			continue
		}
		out.WriteString(scope)
		out.WriteByte(' ')
		out.WriteString(strings.TrimSpace(line[:brace]))
		out.WriteByte(' ')
		out.WriteString(line[brace:])
		out.WriteByte('\n')
	}
}
